module.exports = {
  purge: [],
  theme: {
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      // => @media (min-width: 640px) { ... }
      "sm-phone": "375px",
      "lg-phone": "400px",
    },
    inset: {
      "0": 0,
      "32": "8rem",
      "34": "9rem",
      "36": "10rem",
      "38": "11rem",
      "40": "12rem",
      "42": "13rem",
      "44": "14rem",
      "46": "15rem",
      "48": "16rem",
    },
    backgroundColor: theme => ({
      ...theme("colors"),
      longBreak: "#191c18",
    }),
    fontFamily: {
      "futura-med": "Futura Medium",
      "futura-lite": "Futura Light",
      "futura-bold": "Futura Bold",
      "source-lite": "Source Sans Pro",
    },
    fontSize: {
      xs: ".75rem",
      sm: ".875rem",
      tiny: ".875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "5xl": "3rem",
      "6xl": "4rem",
      "7xl": "5rem",
      "8xl": "6rem",
      "9xl": "7rem",
      "10xl": "8rem",
      "11xl": "9rem",
    },
    extend: {},
  },
  variants: {},
  plugins: [],
}
